Devopstrio test version 3.8.9 27/05/26

diff --git a/.github/workflows/azure-webapp.yml b/.github/workflows/azure-webapp.yml
--- a/.github/workflows/azure-webapp.yml
+++ b/.github/workflows/azure-webapp.yml
@@ -82,12 +82,13 @@ jobs:
       # ==========================================
       - name: Verify QA Secret
         run: |
-          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}" ]; then
-            echo "ERROR: QA Publish Profile Secret Missing"
-            exit 1
-          else
-            echo "QA Publish Profile Secret Found"
-          fi
+            SECRET="${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}"
+              if [ -z "$SECRET" ]; then
+                echo "ERROR: QA Publish Profile Secret Missing"
+                exit 1
+              fi
+              
+               echo "QA Publish Profile Secret Found"
 
       # ==========================================
       # DEPLOY TO QA
